[tool.poetry]
name = "anaximander"
version = "0.5a1"
description = "The rapid application development framework for data-intensive Python"
license = "MPL-2.0"
authors = [
    "Novavia Solutions <info@novavia.us>",
    "JD Margulici <jdmargulici@gmail.com>",
]
readme = "README.md"
homepage = "https://www.anaximander.dev"
repository = "https://github.com/novavia/anaximander"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
]

[tool.poetry.dependencies]
python = ">=3.14,<4.0"
numpy = ">= 2"
pandas = ">= 2"
python-dotenv = "*"
attrs = "^24.2.0"
flask = "^3.1.0"
jinja2 = "^3.1.4"
cookiecutter = "^2.6.0"
sqlalchemy = "^2.0.36"
psycopg2 = "^2.9.10"
runtype = "^0.5.2"
inflect = "^7.5.0"
omegaconf = "^2.3.0"
astpretty = "^3.0.0"

[tool.poetry.dev-dependencies]
black = "*"
ipython = "*"
mypy = "*"
pip = "*"
pytest = "*"
ipykernel = "*"

[tool.poetry.group.dev.dependencies]
pipx = "^1.7.1"
pytest-postgresql = "^6.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
per-file-ignores = { "**/__init__.py" = ["F401", "I001"] }
