#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Init module to Anaximander's meta package.

One of the most salient characteristics of this package is the archetype
model. Archetypes are an implementation of generic types, comparable to
C++ templates. Hence archetypes are abstract base types, whose derived
concrete types are created by supplying them with parameter values. These
parameters are called type parameters. As a dummy example, assume you
create a nested list archetype, such that for a given nested depth there
exists one concrete class. Conceptually, NestedList[0] is a class holding
scalars, NestedList[1] is similar to a simple list, NestedList[2] is
a list of lists, and so on. Here NestedList is declared as an archetype,
with a single type parameter that could be called depth. The derived types
may either be declared explicitly through a class declaration that specifies
the value given to the type parameter as in:

    class NestedList2(NestedList, depth=2):
        ...

Or they can also be created programatically -and even implicitly, by simply
stating NestedList[2].

Generally, the explicit declarative style is preferred when the archetypical
features are not sufficient to fully describe the behavior of the derived
types. It also possible to further specialize a subtype of an archetype.

The interface for creating archetypes is simple: decorate a class with
the @archetype decorator to make it an archetype. The type parameters
are declared in the class declaration, as if they were regular descriptors,
even though they then technically become metaclass-level descriptors.

An archetype can declare multiple type parameters, and each type parameter
has a key argument that can be set True or False. A subtype must provide
non-null values to all type parameters to be considered a concrete type.
However, only the type parameter whose key argument is set to True serve
to register subtypes. Subtype registration is what enables recall by
indexing as in the above example: NestedList[0], NestedList[1], etc...
It is possible for multiple type parameters to be keys, in which case the
registration and retrieval keys are tuples.

Archetypes accept other meta declarations besides type parameters. These
include:

    * Type attributes. These are a less stringent version of type parameters.
    They cannot be used as registration key (i.e. the ability to recall
    a type by bracket notation on the archetype). Another notable difference
    is that a subtype of an archetype whose any type parameter value is unset
    (i.e. it is set to None) is considered abstract and cannot be instantiated.
    By contrast, type attributes can be set to None and still create
    instances, and are hence optional.
    * Metamethods. These are methods declared in an archetype, but transformed
    into metaclass methods. Most notably, methods decorated with the decorators
    'newtypemethod' and 'typeinitmethod' are executed by the metaclass in
    order of declaration, in the __new__ and __init__ methods, respectively.
    These are used to further customize type behavior at type creation.

The archetype system supports inheritance in multiple ways:

    * Types that provide meta declarations (ie. type attributes, parameters,
    metamethods) but are not decorated with the archetype decorator are
    pending archetypes. These are always abstract types (i.e. they cannot
    be instantiated). Any subtype that is decorated with archetype becomes
    an archetype and implements all the meta declarations of the parent type.
    This means that one abstract base type can branc into multiple archetypes.
    * Archetype subtypes can themselves become archetypes. There are generally
    two patterns where this may make sense: 1. A concrete subtype of an
    archetype may declare additional type parameters, in which case there is
    technically no relationship between the two archetype classes except for
    the fact that one concretely inherits from the first one. 2. An
    abstract subtype of an archetype may also become an archetype. In this
    case, the fact that the subtype is abstract means that some of the type
    parameters are unassigned. These type parameters (and only the ones that
    are unassigned in the subtype) then become type parameters in the
    archetype hierarchy generated by the derived archetype. This is again
    a possible necessity of establishing class hierarchies.

The mechanics of archetype creation are not exactly trivial. Here is a short
description to satsify the reader's curiosity and shed some light on the code
contained in this package:

    * Because archetypes are specialized abstract base classes, they must
    have a metaclass that defines them as archetypes;
    * However, this dictates that the concrete types that are derived from an
    archetype cannot have the same metaclass;
    * We resolve this by refering to the archetype-decorated class declaration
    as the basetype. The decorator returns a different class that is the
    archetype.
    * Derived types inherit from the basetype. They still appear to inherit
    from the archetype (i.e. issubclass and isinstance will work as expected),
    but the archetype is in fact a dead end in the class hierarchy.
    * To confer its properties to the archetype, the decorator creates
    a one-time use metaclass mixin. This metaclass mixin is a subclass
    of the base ArcheType mixin metaclass.

This module is part of the Anaximander project.
Copyright (C) Novavia Solutions, LLC.
"""


class NxMetaError(Exception):
    """Customized error for metaprogramming errors."""
    pass


from .nxdescriptors import *
from .nxmetas import *
from .nxtypes import *
from .nxobjects import *
