#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This module defines the root mechanisms of Anaximander's type system.

The most critical and complex aspect of this module is the mechanics
necessary to implement the archetype model.

This module is part of the Anaximander project.
Copyright (C) Novavia Solutions, LLC.
"""

# =============================================================================
# Import statements
# =============================================================================

from collections import OrderedDict, Iterable
import threading

from ..utilities import functions as fun, xprops
from . import NxMetaError
from . import nxdescriptors as nxd

__all__ = []

# Global lock on programmatic subtype creation
LOCK = threading.Lock()

# =============================================================================
# Metaprogramming infrastructure
# =============================================================================


class NxMeta(type):
    """A custom type for Anaximander metaclasses.

    Gotcha: the instances of this class are... metaclasses! This is pushing
    the abstraction of the model to a very unusual extreme and may make it
    difficult to understand right away. However it is worth noting, and
    probably helpful conceptually, that the methods are written using
    the name 'mcl' to refer to instances. For class methods, the designation
    'met' is used to refer to NxMeta itself.
    The method signatures of __new__ and __init__ have been modified to
    incorporate a basename attribute. Basename is a string that is used to
    name types that are programatically generated by instances of NxMeta.
    The NxMeta constructor also accepts an iterable of type attributes -or
    None by default. Type attributes must be of type nxd.TypeAttribute and are
    registered in the typeattributes attribute of the metaclass. Metaclass
    typeattributes become keyword arguments in the constructor of the
    metaclass, and they are also converted into regular descriptors in
    the namespace of the metaclass.
    Type attributes must be explicitly declared in the metaclass creation: in
    other words, they are not passed on through subclassing. This enables
    the possibility that a subtype of an archetype sets values for
    that archetype's type attributes and can itself become an archetype
    while passing on these values.
    """
    __basename__ = 'Nx'
    __archetype__ = None
    __typeattributes__ = OrderedDict()

    def __new__(met, name, bases, namespace, basename=None,
                typeattributes=None):
        return super().__new__(met, name, bases, namespace)

    def __init__(mcl, name, bases, namespace, basename=None,
                 typeattributes=None):
        """Initializes a new metaclass."""
        if basename is not None:
            mcl.__basename__ = basename
        # Binds and registers descriptors
        nxd.MetaDescriptor.collect(mcl, namespace)
        for name, attr in mcl.__metadescriptors__.items():
            # TypeAttributes are treated separately, they must be explicilty
            # declared
            if not isinstance(attr, nxd.TypeAttribute):
                attr.assign(mcl)
        mcl.__typeattributes__ = OrderedDict()
        if typeattributes is not None:
            for attr in typeattributes:
                mcl.__typeattributes__[attr.name] = attr
                attr.assign(mcl)
        # Validates that there is at most one type parameter if it is covariant
        covariant = any(t.covariant for t in mcl.__typeattributes__.values())
        if covariant and len(mcl.typeparameters) > 1:
            msg = "A covariant typeparameter must be single."
            raise NxMetaError(msg)

    def nxm_nxdescriptors(mcl, *types):
        """Returns a mapping of descriptors filtered by types.

        if no types are supplied, then all registered descriptors are
        returned.
        """
        return nxd.NxDescriptor.retrieve(mcl, *types)

    def nxm_metadescriptors(mcl, *types):
        """Returns a mapping of metadescriptors filtered by types.

        if no types are supplied, then all registered metadescriptors are
        returned.
        """
        return nxd.MetaDescriptor.retrieve(mcl, *types)

    @xprops.cachedproperty
    def typeattributes(mcl):
        """Equivalent to __typeattributes__"""
        return OrderedDict(mcl.__typeattributes__)

    @xprops.cachedproperty
    def typeparameters(mcl):
        """The subset of type attributes that are declared as parameters."""
        parameters = fun.vfilter(fun.typecheck(nxd.TypeParameter),
                                 mcl.__typeattributes__)
        return OrderedDict(parameters)

    @xprops.cachedproperty
    def typekeys(mcl):
        """The subset of type parameters that are declared as keys."""
        parameters = fun.vfilter(fun.typecheck(nxd.TypeParameter),
                                 mcl.__typeattributes__)
        keys = fun.vfilter(lambda p: p.key, OrderedDict(parameters))
        return OrderedDict(keys)

    @xprops.cachedproperty
    def nonkeyparameters(mcl):
        """Type parameters that aren't registration keys."""
        return OrderedDict([(k, v) for k, v in mcl.typeparameters.items()
                            if k not in mcl.typekeys])


def nxmeta(basetype, basename=None):
    """A metaclass constructor from a supplied archetypical basetype.

    nxmeta creates a metaclass by subclassing the basetype's metaclass
    and modifiying its behavior based on options that may be found
    in an internal Meta class.
    The constructor also checks for type properties assignments. If the
    basetype has defined values for inherited type attributes, then these
    type attributes are unregistered from the resulting metatype.
    """
    # Collect and update type attributes
    basemeta = type(basetype)
    metadescriptors = OrderedDict(getattr(basemeta, '__metadescriptors__', {}))
    typeattributes = OrderedDict(getattr(basemeta, '__typeattributes__', {}))
    if hasattr(basetype, '__metadescriptors__'):
        for k, v in basetype.__metadescriptors__.items():
            if isinstance(v, nxd.TypeAttribute):
                typeattributes[k] = v
            metadescriptors[k] = v
    for k, v in typeattributes.copy().items():
        if v.is_defined(basetype):
            del typeattributes[k]

    # Assemble NxMeta arguments
    basename = fun.get(basename, basetype.__name__)
    name = basename + 'Type'
    bases = (basemeta,)
    namespace = getattr(basetype, 'Meta', {})
    namespace.update(metadescriptors)
    typeattributes = list(typeattributes.values())
    meta = NxMeta(name, bases, namespace, basename, typeattributes)
    # Assigns the caller's module to the new class by default.
    meta.__module__ = basetype.__module__
    return meta


class ArchMeta(NxMeta):
    """Metaclass for ArcheType mix-in metaclasses."""

    def __new__(met, name, bases, namespace):
        return super().__new__(met, name, bases, namespace)

    def __init__(mcl, name, bases, namespace):
        # Holds an archetype, the only instance of any ArcheType subclass.
        mcl.__archetype__ = None
        # Subtype registry
        mcl.registry = {}
        if not bases:  # mcl is ArcheType, no initialization needed:
            return
        try:
            basetype = namespace['__basetype__']
            metatype = namespace['__metatype__']
            assert issubclass(metatype, type(basetype))
        except (KeyError, AssertionError):
            msg = "Improper ArchMeta declaration."
            raise NxMetaError(msg)


class ArcheType(metaclass=ArchMeta):

    def __new__(mcl, name, bases, namespace, **kwargs):
        """Emulates NxType.__new__ as the arguments are redirected."""
        if mcl is ArcheType:
            msg = "Cannot instantiate abstract metaclass ArcheType."
            raise NxMetaError(msg)
        if mcl.__archetype__ is None:
            # In this case all arguments are ignored and the __archetype__
            # instance is created.
            basetype = mcl.__basetype__
            name = basetype.__name__
            bases = (basetype,)
            archetype = super().__new__(mcl, name, bases, {}, **kwargs)
            archetype.__module__ = basetype.__module__
            # Set the archetype on mcl and __metatype__
            mcl.__metatype__.__archetype__ = archetype
            mcl.__archetype__ = archetype
            # Adds TypeAttributeProperties to basetype for type attributes
            base_typeattributes = getattr(basetype, '__typeattributes__', {})
            for k, v in mcl.__metadescriptors__.items():
                # This checks that the typeattribute isn't a carryover
                # from a parent archetype, in which case this step is skipped.
                if isinstance(v, nxd.TypeAttribute):
                    if not base_typeattributes.get(k, None) == v:
                        v.set_instance_property(basetype)
                    setattr(archetype, v.cache, None)
                # Removes processed metadescriptors from the basetype.
                else:
                    try:
                        delattr(basetype, k)
                    except AttributeError:
                        pass
            return archetype
        else:
            cls = mcl.__metatype__(name, bases, namespace, **kwargs)
            return cls

    def __init__(archetype, name, bases, namespace, **kwargs):
        archetype.__archetype__ = archetype
        basetype = archetype.__basetype__
        # If basetype was itself registered with its own archetype,
        # the newly formed archetype takes over as the decorated class.
        try:
            base_archetype = basetype.archetype
            registered = base_archetype.registry[basetype.registration_key]
            assert registered is basetype
        except (AttributeError, KeyError, AssertionError):
            pass
        else:
            base_archetype.registry[basetype.registration_key] = archetype

    def nxregister(archetype, cls, overtype=False):
        """Registers a subtype.

        Attrs:
            cls: a newly created subtype of the archetype.
            overtype: if False, cls is only written in the registry if
                no extant type has been registered with the same
                type parameter values.
        """
        with LOCK:
            if cls.__bases__[0] is archetype.__basetype__:
                archetype.register(cls)  # registration per abc module.
            registry = type(archetype).registry
            registration_key = cls.registration_key
            if registration_key is None:
                return
            if registration_key not in registry or overtype is True:
                registry[registration_key] = cls

    def __getitem__(archetype, key):
        """Enables to retrieve subtypes from the registry.

        If not found, the subtype is opportunistically created.
        """
        try:
            subtype = type(archetype).registry[key]
        except KeyError:
            if isinstance(key, Iterable):
                parameters = key
            else:
                parameters = (key,)
            kwargs = dict(zip(type(archetype).typekeys, parameters))
            try:
                subtype = archetype.subtype(**kwargs)
                assert not subtype.abstract
            except Exception as e:
                msg = f"Could not create derived type with parameters {key}."
                raise NxMetaError(msg)
        return subtype

    @property
    def clade(archetype):
        """Returns an iterable of registered subclasses."""
        return type(archetype).registry.values()


def archmeta(basetype, basename=None):
    """An Archetype factory function."""
    basename = fun.get(basename, basetype.__name__)
    metatype = nxmeta(basetype, basename)
    name = basename + 'ArcheType'
    bases = (ArcheType, metatype)
    namespace = {'__basetype__': basetype,
                 '__metatype__': metatype}
    meta = ArchMeta(name, bases, namespace)
    meta.__module__ = basetype.__module__
    return meta
