#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This module defines the root mechanisms of Anaximander's type system.

The most critical and complex aspect of this module is the mechanics
necessary to implement the archetype model.

This module is part of the Anaximander project.
Copyright (C) Novavia Solutions, LLC.
"""

# =============================================================================
# Import statements
# =============================================================================

from collections import OrderedDict
import threading

from ..utilities import functions as fun
from . import NxMetaError
from . import nxdescriptors as nxd

__all__ = []

# Global lock on programmatic subtype creation
LOCK = threading.Lock()

# =============================================================================
# Metaprogramming infrastructure
# =============================================================================


class NxMeta(type):
    """A custom type for Anaximander metaclasses.

    Gotcha: the instances of this class are... metaclasses! This is pushing
    the abstraction of the model to a very unusual extreme and may make it
    difficult to understand right away. However it is worth noting, and
    probably helpful conceptually, that the methods are written using
    the name 'mcl' to refer to instances. For class methods, the designation
    'met' is used to refer to NxMeta itself.
    The method signatures of __new__ and __init__ have been modified to
    incorporate a basename attribute. Basename is a string that is used to
    name types that are programatically generated by instances of NxMeta.
    The namespace passed to NxMeta may contain metacharacters, which
    are then registered in order to customize new type creation.
    The NxMeta constructor also accepts an iterable of metacharacters -or
    None by default. Metacharacters must be of type nxd.MetaCharacter and are
    registered in the metacharacters attribute of the metaclass. Metaclass
    metacharacters become keyword arguments in the constructor of the
    metaclass, and they are also converted into TypeCharacter descriptors.
    Metacharacters must be explicitly declared in the metaclass creation: in
    other words, they are not passed on through subclassing. This enables
    the possibility that a subtype of an archetype sets values for
    that archetype's metacharacters and can itself become an archetype
    while passing on these values.
    """
    basename = 'Nx'
    metacharacters = OrderedDict()

    def __new__(met, name, bases, namespace, basename=None,
                metacharacters=None):
        return super().__new__(met, name, bases, namespace)

    def __init__(mcl, name, bases, namespace, basename=None,
                 metacharacters=None):
        """Initializes a new metaclass."""
        if basename is not None:
            mcl.basename = basename
        # Binds and registers descriptors
        nxd.TypeDescriptor.register(mcl, namespace)
        mcl.metacharacters = OrderedDict()
        if metacharacters is not None:
            for mchar in metacharacters:
                mcl.metacharacters[mchar.name] = mchar
                typecharacter = mchar.transfer(mcl)
                mcl.__typedescriptors__[typecharacter.name] = typecharacter

    def typedescriptors(mcl, *types):
        """Returns a mapping of typedescriptors filtered by types.

        if no types are supplied, then all registered typedescriptors are
        returned.
        """
        if not types:
            types = (nxd.TypeDescriptor,)
        descriptors = fun.vfilter(fun.typecheck(*types),
                                  mcl.__typedescriptors__)
        return OrderedDict(descriptors)


def nxmeta(basetype, basename=None):
    """A metaclass constructor from a supplied archetypical basetype.

    nxmeta creates a metaclass by subclassing the basetype's metaclass
    and modifiying its behavior based on options that may be found
    in an internal Meta class.
    The constructor also checks for type properties assignments. If the
    basetype has defined values for inherited metacharacters, then these
    metacharacters are unregistered from the resulting metatype.
    """
    # Collect and update metacharacters
    basemeta = type(basetype)
    metacharacters = OrderedDict(getattr(basemeta, 'metacharacters', {}))
    for k in metacharacters:
        if getattr(basetype, k, None) is not None:
            del metacharacters[k]
    if hasattr(basetype, '__metadescriptors__'):
        for k, v in basetype.__metadescriptors__.items():
            metacharacters[k] = v

    # Assemble NxMeta arguments
    basename = fun.get(basename, basetype.__name__)
    name = basename + 'Type'
    bases = (basemeta,)
    namespace = getattr(basetype, 'Meta', {})
    metacharacters = list(metacharacters.values())
    meta = NxMeta(name, bases, namespace, basename, metacharacters)
    # Assigns the caller's module to the new class by default.
    meta.__module__ = basetype.__module__
    return meta


class ArchMeta(NxMeta):
    """Metaclass for ArcheType mix-in metaclasses."""

    def __new__(met, name, bases, namespace):
        return super().__new__(met, name, bases, namespace)

    def __init__(mcl, name, bases, namespace):
        # Holds an archetype, the only instance of any ArcheType subclass.
        mcl.__archetype__ = None
        # Subtype registry
        mcl.registry = {}
        if not bases:  # mcl is ArcheType, no initialization needed:
            return
        try:
            basetype = namespace['__basetype__']
            metatype = namespace['__metatype__']
            assert issubclass(metatype, type(basetype))
        except (KeyError, AssertionError):
            msg = "Improper ArchMeta declaration."
            raise NxMetaError(msg)


class ArcheType(metaclass=ArchMeta):

    def __new__(mcl, name, bases, namespace, **kwargs):
        """Emulates NxType.__new__ as the arguments are redirected."""
        if mcl is ArcheType:
            msg = "Cannot instantiate abstract metaclass ArcheType."
            raise NxMetaError(msg)
        if mcl.__archetype__ is None:
            # In this case all arguments are ignored and the __archetype__
            # instance is created.
            name = mcl.__basetype__.__name__
            bases = (mcl.__basetype__,)
            archetype = super().__new__(mcl, name, bases, {}, **kwargs)
            archetype.__module__ = mcl.__basetype__.__module__
            # Set the archetype on mcl and __metatype__
            mcl.__metatype__.__archetype__ = archetype
            mcl.__archetype__ = archetype
            return archetype
        else:
            cls = mcl.__metatype__(name, bases, namespace, **kwargs)
            return cls

    def __init__(archetype, name, bases, namespace, **kwargs):
        archetype.__archetype__ = archetype

    def nxregister(archetype, cls, overtype=False):
        """Registers a subtype.

        Attrs:
            cls: a newly created subtype of the archetype.
            overtype: if False, cls is only written in the registry if
                no extant type has been registered with the same
                metacharacter values.
        """
        with LOCK:
            cls.__archetype__ = archetype
            registry = type(archetype).registry
            characters = cls.metacharacters
            extant = registry.get(characters, None)
            if extant is None or overtype is True:
                registry[characters] = cls
            type(archetype).registry.register(cls)
            if cls.__bases__[0] is archetype.__basetype__:
                archetype.register(cls)  # registration per abc module.

    def __getitem__(archetype, *characters):
        """Enables to retrive subtypes from the registry."""
        return type(archetype).registry[characters]


def archmeta(basetype, basename=None):
    """An Archetype factory function."""
    basename = fun.get(basename, basetype.__name__)
    metatype = nxmeta(basetype, basename)
    name = basename + 'ArcheType'
    bases = (ArcheType, metatype)
    namespace = {'__basetype__': basetype,
                 '__metatype__': metatype}
    meta = ArchMeta(name, bases, namespace)
    meta.__module__ = basetype.__module__
    return meta
