#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This module defines the root mechanisms of Anaximander's type system.

This module is part of the Anaximander project.
Copyright (C) Novavia Solutions, LLC.
"""

# =============================================================================
# Import statements
# =============================================================================

import itertools

from ..utilities import functions as fun
from ..registries import registries as nrg
from .metadescriptors import metaregistries

# =============================================================================
# NxMeta metaclass type
# =============================================================================


class MetaError(Exception):
    """A specialized exception for metatyping errors."""
    pass


class NxMeta(type):
    """A custom type for Anaximander metaclasses.

    Gotcha: the instances of this class are... metaclasses! This is pushing
    the abstraction of the model to a very unusual extreme and may make it
    difficult to understand right away. However it is worth noting, and
    probably helpful conceptually, that the methods are written using
    the name 'mcl' to refer to instances. For class methods, the designation
    'met' is used to refer to NxMeta itself.
    The method signatures of __new__ and __init__ have been modified to
    incorporate a basename attribute and optional metadescriptors attribute.
    * basename is a string that is used to name types that are programatically
    generated by instances of NxMeta. In case that a metaclass is
    subclassed by declaration, it will seek a __basename__ declaration in its
    body, or inherit its basename from its parent metaclass.
    * metadescriptors is either None or an iterable of MetaDescriptor
    instances that get called by the __init__ method and may modify the
    namespace of the NxMeta instance accordingly.
    """
    __archetype__ = None  # Ensures the attribute exists on all metaclasses.

    def __new__(met, name, bases, namespace,
                basename=None, metadescriptors=None):
        return super().__new__(met, name, bases, namespace)

    def __init__(mcl, name, bases, namespace,
                 basename=None, metadescriptors=None):
        """Initializes a new metaclass."""
        if basename is not None:
            mcl.__basename__ = basename
        mcl.metaregistries = {}
        for mdtype, factory in metaregistries.items():
            registry = factory(mcl)  # creates a metaregistry in the metaclass
            mcl.metaregistries[mdtype] = registry
        if metadescriptors is not None:
            for md in metadescriptors:
                md(mcl)  # Binds the metadescriptor to the metaclass
        mcl.__counter__ = itertools.count()  # A type counter


def nxmeta(basetype):
    """A metaclass constructor from a supplied archetypical basetype.

    nxmeta creates a metaclass by subclassing the basetype's metaclass
    and modifiying its behavior based on any metadescriptors found
    in the archetype's declarations.
    """
    basename = basetype.__name__
    name = basename + 'Type'
    bases = (type(basetype),)
    try:
        metadescriptors = basetype.__metadeclarations__.values()
    except AttributeError:
        metadescriptors = None
    return NxMeta(name, bases, {}, basename, metadescriptors)

# =============================================================================
# ArcheType metaclass
# =============================================================================


class ArchMeta(NxMeta):
    """The [meta-]metaclass for ArcheType.

    Its behaviors are as follows:
    * Sets __archetype__ to None
    * Ensures that the new metaclass has proper __basetype__ and
    __metatype__ attributes. __basetype__ is a declared NxType that
    has been decorated by archetype and will be subclassed to create the
    __archetype__ instance. __metatype__ is the metaclass responsible for
    creating subtypes of the __archetype__. It is normally created by
    nxmeta.
    """

    def __new__(met, name, bases, namespace):
        return super().__new__(met, name, bases, namespace)

    def __init__(mcl, name, bases, namespace):
        # Holds an archetype, the only instance of any ArcheType subclass.
        mcl.__archetype__ = None
        try:
            basetype = namespace['__basetype__']
            metatype = namespace['__metatype__']
            assert isinstance(type(basetype), NxMeta)
            assert isinstance(metatype, NxMeta)
        except (KeyError, AssertionError):
            if name in ('ArcheType', 'ProtoType'):
                return
            msg = "Improper ArchMeta declaration."
            raise MetaError(msg)


class ArcheType(metaclass=ArchMeta):
    """A special metatype base class for archetypical classes.

    In order to enable the archetype machinery, a special metaclass needs
    to be created for each declared archetype. Here is a summary explanation:
    * Archetypes are created by decorating a class declaration. That class
    is created with a metaclass that is supplied by its inheritance structure,
    and is NxType by default.
    * One of the functionalities enabled by archetypes is the declaration of
    metadescriptors that are passed to a metaclass used to create derived
    classes. This suggests that the metaclass for derived classes is
    different than the one used by the archetype's class declaration.
    * Hence in order to set the proper metaclass for subclasses of an
    archetype, that archetype needs to be modified. What we do is we
    create a special metaclass that inherits from the base ArcheType metaclass.
    The archetype decorator returns a class that looks like what the programmer
    declared but is an instance of that metaclass.
    * ArcheType and its subclasses are intended as singleton: their only
    instance is an archetype. This is why these classes have a __archetype__
    attribute that is used to hold that single instance.
    * The archetype's metaclass being an ArcheType subclass, it will get
    called when we subclass the archetype. For that reason, the __new__
    method is constructed to redirect class creation to a functional
    metaclass once the singleton archetype has been created.

    Strict archetypes cannot declare metacharacters, but this is enabled
    by ProtoType, which specializes ArcheType.
    """
    __basetype__ = None
    __metatype__ = None
    __overtype__ = True  # Default setting, can be overriden in declarations.

    def __new__(mcl, name, bases, namespace, **kwargs):
        """Emulates NxType.__new__ as the arguments are redirected."""
        if mcl in (ArcheType, ProtoType):
            msg = "Cannot instantiate abstract class ArcheType."
            raise MetaError(msg)
        if mcl.__archetype__ is None:
            # In this case all arguments are ignored and the __archetype__
            # instance is created.
            name = mcl.__basetype__.__name__
            bases = (mcl.__basetype__,)
            archetype = super().__new__(mcl, name, bases, {})
            archetype.__module__ = mcl.__basetype__.__module__
            # Set the archetype on mcl and __metatype__
            # This is a bit overkill since mcl inherits from __metatype__
            # but it is also safer.
            mcl.__metatype__.__archetype__ = archetype
            mcl.__archetype__ = archetype
            return archetype
        else:
            cls = mcl.__metatype__(name, bases, namespace, **kwargs)
            return cls

    def __init__(archetype, name, bases, namespace):
        archetype.__archetype__ = archetype
        metacharacters = archetype.__metacharacters__
        if metacharacters:
            msg = "ArcheTypes do not accept metacharacters, use a " + \
                "ProtoType instead."
            raise MetaError(msg)
        archetype.type_registry = ArchRegistry()

    def nxregister(archetype, cls, **kwargs):
        cls.__archetype__ = archetype
        archetype.type_registry.register(cls)
        if cls.__bases__[0] is archetype.__basetype__:
            archetype.register(cls)  # registration per abc module.
        return cls

    @property
    def subtypes(archetype):
        """Returns an iterable of registered clade types."""
        return archetype.type_registry.values()


# TODO: could make prototypes smarter by allowing metacharacters
# to be passed as keyword arguments in instantiation calls and directing
# the call to the proper subtype.
def protonew(cls, *args, **kwargs):
    """Implementation of __new__ for ProtoTypes."""
    raise TypeError("Cannot instantiate an prototype.")


class ProtoType(ArcheType):
    """A ProtoType is an ArcheType that declares metacharacters.

    Prototypes declare one or more metacharacters whose values differentiate
    the derived types of the archetype. Derived types are registered in a
    type_registry, with a key that is a tuple of its metacharacter values.
    By default, overtyping is allowed. Hence if an existing derived type
    of an archetype is further subclassed with the same metacharacters, it
    will take precedence over the previous version and replace it in the
    type_registry. This setting can be modified in one of two ways:
    * The archetype itself can declare __overtype__ = False, in which case
    overtyping is generally forbidden for the corresponding clade.
    * Otherwise, new types can be declared with the keyword argument overtype,
    in which case whatever value is passed (True or False) will override the
    clade's default behavior.
    """

    def __init__(prototype, name, bases, namespace):
        prototype.__archetype__ = prototype
        metacharacters = prototype.__metacharacters__
        overtype = prototype.__overtype__
        prototype.type_registry = ProtoRegistry(*metacharacters,
                                                overtype=overtype)
        prototype.__new__ = classmethod(protonew)

    def nxregister(prototype, cls, **kwargs):
        if any(v is None for v in cls.metacharacters):
            msg = "Derived types of an prototype must declare non-None " + \
                "values for all metacharacters."
            raise MetaError(msg)
        cls.__archetype__ = prototype
        overtype = kwargs.get('overtype', None)
        prototype.type_registry.register(cls, *cls.metacharacters,
                                         overtype=overtype)
        if cls.__bases__[0] is prototype.__basetype__:
            prototype.register(cls)  # registration per abc module.
        return cls

    def __getitem__(prototype, key):
        """A convenience function to pull types from the type registry."""
        if isinstance(key, tuple):
            try:
                return prototype.type_registry.get(*key)
            except KeyError:
                kwargs = dict(zip(prototype.__metacharacters__, key))
                return prototype.subtype(**kwargs)
        try:
            return prototype.type_registry.get(key)
        except KeyError:
            kwargs = dict(zip(prototype.__metacharacters__, [key]))
            return prototype.subtype(**kwargs)

    @property
    def subtypes(prototype):
        """Returns an iterable of registered clade types."""
        return prototype.type_registry.root.titles(root=False)


def archmeta(basetype, prototype=False):
    """An ArcheMeta factory function."""
    metatype = nxmeta(basetype)
    name = basetype.__name__ + ('ProtoType' if prototype else 'ArcheType')
    archmetatype = ProtoType if prototype else ArcheType
    bases = (archmetatype, metatype)
    namespace = {'__basetype__': basetype,
                 '__metatype__': metatype}
    return ArchMeta(name, bases, namespace)


def protometa(basetype):
    """A ProtoMeta factory function."""
    return archmeta(basetype, True)

# =============================================================================
# Type registry for clades
# =============================================================================


class ArchRegistry(nrg.Pool):
    """A Pool to register subtypes of an ArcheType."""
    pass


class ProtoRegistry(nrg.Hierarchy):
    """A specialized Hierarchy to register subtypes of a ProtoType."""

    def __init__(self, *layer_names, overtype=True):
        """Augments super with the overtype parameter.

        if overtype is True, then types that are registered with a key
        that is already in the type_registry overwrite the existing type.
        Otherwise a RegistrationError is raised.
        """
        super().__init__(*layer_names)
        self.overtype = overtype

    def register(self, obj, *args, overtype=None, **kwargs):
        """Adds the overtype parameter to determine whether to overwrite.

        Optional overtype parameter overrides self's default setting.
        """
        overtype = fun.get(overtype, self.overtype)
        if overtype is False:
            try:
                cls = self.get(*args, **kwargs)
            except KeyError:
                pass
            else:
                if isinstance(cls, type):
                    msg = "{0} is already registered with the same " + \
                        "metacharacters as {1}"
                    raise nrg.RegistrationError(msg.format(cls, obj))
        super().register(obj, *args, **kwargs)
