#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This module defines the root mechanisms of Anaximander's type system.

This module is part of the Anaximander project.
Copyright (C) Novavia Solutions, LLC.
"""

# =============================================================================
# Import statements
# =============================================================================

from abc import ABC, ABCMeta
import itertools

# =============================================================================
# NxMeta metaclass type
# =============================================================================


# TODO: add TypeRegistry
class NxMeta(ABCMeta):
    """A custom type for Anaximander metaclasses.

    Gotcha: the instances of this class are... metaclasses! This is pushing
    the abstraction of the model to a very unusual extreme and may make it
    difficult to understand right away. However it is worth noting, and
    probably helpful conceptually, that the methods are written using
    the name 'mcl' to refer to instances. For class methods, the designation
    'met' is used to refer to NxMeta itself.
    The method signatures of __new__ and __init__ have been modified to
    incorporate a basename attribute and optional metadescriptors attribute.
    * basename is a string that is used to name types that are programatically
    generated by instances of NxMeta. In case that a metaclass is
    subclassed by declaration, it will seek a __basename__ declaration in its
    body, or inherit its basename from its parent metaclass.
    * metadescriptors is either None or an iterable of MetaDescriptor
    instances that get called by the __init__ method and may modify the
    namespace of the NxMeta instance accordingly.
    """

    def __new__(met, name, bases, namespace,
                basename=None, metadescriptors=None):
        return type.__new__(met, name, bases, namespace)

    def __init__(mcl, name, bases, namespace,
                 basename=None, metadescriptors=None):
        """Initializes a new metaclass."""
        if basename is not None:
            mcl.__basename__ = basename
        if metadescriptors is not None:
            for md in metadescriptors:
                md(mcl)  # Binds the metadescriptor to the metaclass
        mcl.__counter__ = itertools.count()  # A type counter


def nxmeta(basetype):
    """A metaclass constructor from a supplied archetypical basetype.

    nxmeta creates a metaclass by subclassing the basetype's metaclass
    and modifiying its behavior based on any metadescriptors found
    in the archetype's declarations.
    """
    basename = basetype.__name__
    name = basename + 'Type'
    bases = (type(basetype),)
    try:
        metadescriptors = basetype.__metadescriptors__.values()
    except AttributeError:
        metadescriptors = None
    return NxMeta(name, bases, {}, basename, metadescriptors)

# =============================================================================
# ArcheType metaclass
# =============================================================================


class ArchMeta(NxMeta):
    """The [meta-]metaclass for ArcheType.

    Its behaviors are as follows:
    * Sets __archetype__ to None
    * Ensures that the new metaclass has proper __basetype__ and
    __metatype__ attributes. __basetype__ is a declared NxType that
    has been decorated by archetype and will be subclassed to create the
    __archetype__ instance. __metatype__ is the metaclass responsible for
    creating subtypes of the __archetype__. It is normally created by
    nxmeta.
    """

    def __new__(met, name, bases, namespace):
        return type.__new__(met, name, bases, namespace)

    def __init__(mcl, name, bases, namespace):
        # Holds an archetype, the only instance of any ArcheType subclass.
        mcl.__archetype__ = None
        try:
            basetype = namespace['__basetype__']
            metatype = namespace['__metatype__']
            assert isinstance(type(basetype), NxMeta)
            assert isinstance(metatype, NxMeta)
        except (KeyError, AssertionError):
            if name in ('ArcheType', 'ProtoType'):
                return
            msg = "Improper ArchMeta declaration."
            raise TypeError(msg)


# TODO: could make archetype / prototype smarter by allowing metacharacters
# to be passed as keyword arguments in calls and directing instantiation
# to the proper subtype.
class ArcheType(metaclass=ArchMeta):
    """A special metatype base class for archetypical classes.

    In order to enable the archetype machinery, a special metaclass needs
    to be created for each declared archetype. Here is a summary explanation:
    * Archetypes are created by decorating a class declaration. That class
    is created with a metaclass that is supplied by its inheritance structure,
    and is NxType by default.
    * One of the functionalities enabled by archetypes is the declaration of
    metadescriptors that are passed to a metaclass used to create derived
    classes. This suggests that the metaclass for derived classes is
    different than the one used by the archetype's class declaration.
    * Hence in order to set the proper metaclass for subclasses of an
    archetype, that archetype needs to be modified. What we do is we
    create a special metaclass that inherits from the base ArcheType metaclass.
    The archetype decorator returns a class that looks like what the programmer
    declared but is an instance of that metaclass.
    * ArcheType and its subclasses are intended as singleton: their only
    instance is an archetype. This is why these classes have a __archetype__
    attribute that is used to hold that single instance.
    * The archetype's metaclass being an ArcheType subclass, it will get
    called when we subclass the archetype. For that reason, the __new__
    method is constructed to redirect class creation to a functional
    metaclass once the singleton archetype has been created.
    """
    __basetype__ = None
    __metatype__ = None

    def __new__(mcl, name, bases, namespace, **kwargs):
        """Emulates NxType.__new__ as the argumenst are redirected."""
        if mcl in (ArcheType, ProtoType):
            msg = "Cannot instantiate abstract classes ArcheType / ProtoType."
            raise TypeError(msg)
        if mcl.__archetype__ is None:
            # In this case all arguments are ignored and the __archetype__
            # instance is created.
            name = mcl.__basetype__.__name__
            bases = (mcl.__basetype__,)
            archetype = type.__new__(mcl, name, bases, {})
    #        archetype.__module__ = mcl.__basetype__.__module__
            mcl.__archetype__ = archetype
            return mcl.__archetype__
        else:
            if not bases == (mcl.__archetype__,):
                msg = "Incorrect use of an ArcheType subclass."
                raise TypeError(msg)
            basetype = mcl.__basetype__
            cls = mcl.__metatype__(name, (basetype,), namespace, **kwargs)
            mcl.__archetype__.register(cls)
            return cls

    def __init__(archetype, name, bases, namespace):
        archetype.__archetype__ = archetype

    # TODO: also register cls in the type registry
    def register(archetype, cls):
        # Hacking abc registration but not fully understanding it.
        archetype._abc_registry.add(cls)
        archetype._abc_cache.add(cls)
        ABCMeta._abc_invalidation_counter += 1  # Invalidate negative cache
        cls.__archetype__ = archetype
        return cls


def protonew(cls, *args, **kwargs):
    """Implementation of __new__ for ProtoTypes."""
    raise TypeError("Cannot instantiate a prototype.")


class ProtoType(ArcheType):
    """A metatype base class for prototypical classes.

    ProtoTypes differ from ArcheTypes in that they cannot be instantiated.
    To enforce this behavior, the metaclass modifies the __new__ method
    of the archetype accordingly.
    """

    def __init__(archetype, name, bases, namespace):
        super().__init__(name, bases, namespace)
        archetype.__new__ = classmethod(protonew)


def archmeta(basetype, prototype=False):
    """An ArcheMeta factory function."""
    metatype = nxmeta(basetype)
    name = basetype.__name__ + 'ArcheType'
    archmetatype = ProtoType if prototype else ArcheType
    bases = (archmetatype, metatype)
    namespace = {'__basetype__': basetype,
                 '__metatype__': metatype}
    return ArchMeta(name, bases, namespace)


def protometa(basetype):
    """A ProtoMeta factory function."""
    return archmeta(basetype, True)
